INSERT INTO employees (name, position, department, email, age) VALUES ('Ivan', 'intern', 'A', 'ivan@job.com', 21);
INSERT INTO employees (name, position, department, email, age) VALUES ('Olga', 'intern', 'B', 'olga@job.com', 2);
INSERT INTO employees (name, position, department, email, age) VALUES ('Dmitriy', 'software engineer', 'A', 'dmitriy@job.com', 29);
INSERT INTO employees (name, position, department, email, age) VALUES ('Maria', 'intern', 'B', 'maria@job.com', 23);
INSERT INTO employees (name, position, department, email, age) VALUES ('Oleg', 'QA', 'A', 'oleg@job.com', 35);
INSERT INTO employees (name, position, department, email, age) VALUES ('Ignat', 'software engineer', 'B', 'ignat@job.com', 53);
INSERT INTO employees (name, position, department, email, age) VALUES ('Magamed', 'intern', 'A', 'magamed@job.com', 33);
INSERT INTO employees (name, position, department, email, age) VALUES ('Vladimir', 'president', 'A', 'vladimir@job.com', 70);
INSERT INTO employees (name, position, department, email, age) VALUES ('Anton', 'senior software engineer', 'B', 'anton@job.com', 27);
INSERT INTO employees (name, position, department, email, age) VALUES ('Michail', 'vice president', 'B', 'michail@job.com', 67);
INSERT INTO employees (name, position, department, email, age) VALUES ('Anna', 'intern', 'B', 'ivan@job.com', 24);
INSERT INTO employees (name, position, department, email, age) VALUES ('Andrey', 'software engineer', 'A', 'andrey@job.com', 28);
INSERT INTO employees (name, position, department, email, age) VALUES ('Sergey', 'QA', 'A', 'sergey@job.com', 19);